server:
    port: 21601

security:
  basic:
    enabled: true
#log
logging:
  level:
    cn:
      nutz: info
      flow: info
    org:
      springframework:
        transaction: info
        web: info
      flowable: info
#spring
spring:
  application:
    name: flowable-flow
  redis:
    database: 0
    host: 62.234.137.124
    password: YQ950109cjd941001
    port: 56679
  rabbitmq:
    host: 62.234.137.124
    port: 5672
    username: root
    password: YQ950109cjd941001
  datasource:
    url: jdbc:mysql://62.234.137.124:56612/workflow_new?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: YQ950109cjd941001
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: SELECT 'x'
      validation-query-timeout: 6000
      test-on-borrow: false
      test-on-return: false
    tomcat:
      min-evictable-idle-time-millis: 300000
      max-active: 20
      initial-size: 5
      max-wait:  60000
      min-idle: 5
      validation-query: SELECT 'x'
      validation-query-timeout: 6000
      test-on-borrow: false
      test-on-return: false

  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate.ddl-auto: none
    hibernate:
      naming:
        strategy: cn.flow.server.mysql.MySQLNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

management:
  endpoint:
    flowable:
      enabled: true

flowable:
  idm:
    enabled: false
  cmmn:
    enabled: false
  content:
    enabled: false
  dmn:
    enabled: false
  form:
    enabled: true
  database-schema-update: false
#  database-schema-update: false

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://192.168.1.44:10100/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒） 超过5秒自动注销eureka中的服务
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    ip-address: 172.16.85.47